//console.log(document);
//console.log(document.head);
//console.log(document.body);
//console.log(document.title);
//console.log(document.head.parentNode);
//console.log(document.head.nextSibling.nextSibling);
//console.log(document.body.firstChild);
//console.log(document.body.childNodes[1]);
//let children = document.body.childNodes;
//console.log(typeof(children));
//children.forEach( x => console.log(x) );
//children.map( x => x + x);
//console.log(document.body.childNodes[3]);
console.log(document.body.children[1]);